SharpIni: SharpIni.Document Class Reference
SharpIni.Document Class Reference
Public Member Functions
Document ()
bool Contains (string section)
bool Contains (string section, string key)
Section Get (string section)
Key Get (string section, string key)
bool Add (Section section, bool replace=false)
bool Add (string section, Key key, bool create=true, bool replace=false)
bool Remove (string section)
bool Remove (string section, string key)
void Clear ()
bool LoadFromFile (string path)
Properties
Section this[string name] [get, set]
bool Empty [get]
int Count [get]
Dictionary< string, Section > Sections [get]
Constructor & Destructor Documentation
Document()
SharpIni.Document.Document ()
Member Function Documentation
Add() [1/2]
bool SharpIni.Document.Add (Section section, bool replace = false)
References SharpIni.Document.Contains(), SharpIni.Naming.IsValid(), and SharpIni.Section.Name.
Add() [2/2]
bool SharpIni.Document.Add (string section, Key key, bool create = true, bool replace = false)
References SharpIni.Document.Add(), SharpIni.Document.Contains(), SharpIni.Naming.IsValid(), and SharpIni.Key.Name.
Clear()
void SharpIni.Document.Clear ()
Contains() [1/2]
bool SharpIni.Document.Contains (string section)
Contains() [2/2]
bool SharpIni.Document.Contains (string section, string key)
References SharpIni.Document.Contains().
Get() [1/2]
Section SharpIni.Document.Get (string section)
References SharpIni.Document.Contains().
Get() [2/2]
Key SharpIni.Document.Get (string section, string key)
References SharpIni.Document.Contains().
LoadFromFile()
bool SharpIni.Document.LoadFromFile (string path)
References SharpIni.Document.Add(), SharpIni.Section.CreateFromLine(), SharpIni.Key.CreateFromLine(), and SharpIni.Debug.Log().
Remove() [1/2]
bool SharpIni.Document.Remove (string section)
Remove() [2/2]
bool SharpIni.Document.Remove (string section, string key)
References SharpIni.Document.Contains().
Property Documentation
Count
int SharpIni.Document.Count get
Empty
bool SharpIni.Document.Empty get
Sections
Dictionary<string, Section> SharpIni.Document.Sections get
this[string name]
Section SharpIni.Document.this[string name] get set
The documentation for this class was generated from the following file:
SharpIni/Document.cs