SharpIni: SharpIni.Section Class Reference
SharpIni.Section Class Reference
A section/header containing a name and the Keys it owns.
Public Member Functions
Section (string name=null)
Constructs the section with an optional name.
bool Contains (string name)
Key Get (string name)
bool Add (Key key, bool replace=false)
bool Remove (string name)
void Clear ()
bool LoadNameFromLine (string line)
bool LoadKeyFromLine (string line, bool replace=false)
Static Public Member Functions
static Section CreateFromLine (string line)
Properties
Key this[string name] [get, set]
Allows access to sections' Keys by name.
string Name [get, set]
Dictionary< string, Key > Keys [get]
bool Empty [get]
int Count [get]
Detailed Description
A section/header containing a name and the Keys it owns.
Constructor & Destructor Documentation
Section()
SharpIni.Section.Section (string name = null)
Constructs the section with an optional name.
Parameters
name The name of the section.
References SharpIni.Naming.IsValid().
Member Function Documentation
Add()
bool SharpIni.Section.Add (Key key, bool replace = false)
References SharpIni.Section.Contains(), SharpIni.Naming.IsValid(), and SharpIni.Key.Name.
Clear()
void SharpIni.Section.Clear ()
Contains()
bool SharpIni.Section.Contains (string name)
CreateFromLine()
static Section SharpIni.Section.CreateFromLine (string line) static
References SharpIni.Section.LoadNameFromLine(), and SharpIni.Section.Section().
Get()
Key SharpIni.Section.Get (string name)
References SharpIni.Section.Contains().
LoadKeyFromLine()
bool SharpIni.Section.LoadKeyFromLine (string line, bool replace = false)
References SharpIni.Section.Add(), and SharpIni.Key.LoadFromLine().
LoadNameFromLine()
bool SharpIni.Section.LoadNameFromLine (string line)
References SharpIni.Section.Name.
Remove()
bool SharpIni.Section.Remove (string name)
Property Documentation
Count
int SharpIni.Section.Count get
Empty
bool SharpIni.Section.Empty get
Keys
Dictionary<string, Key> SharpIni.Section.Keys get
Name
string SharpIni.Section.Name get set
this[string name]
Key SharpIni.Section.this[string name] get set
Allows access to sections' Keys by name.
When assigning a Key, Add(Key, bool) will be called with the replace parameter set to true.
Parameters
name The name of the Key to find.
Exceptions
ArgumentException Thrown when assigning if the call to Add(Key, bool) fails or if the name does not have the same name as the value.
Returns
Returns a key with the given name if it is contained by the instance.
The documentation for this class was generated from the following file:
SharpIni/Section.cs