SharpIni: SharpIni.Key Class Reference
SharpIni.Key Class Reference
A key/property containing a name and value.
Public Member Functions
Key (string name=null, string value=null)
Constructs the instance with an optional name and value.
bool LoadFromLine (string line)
Parses a line from a file and assigns the data to the instance.
Int64 ToInt64 ()
Returns Value parsed as a 64-bit signed integer.
UInt64 ToUInt64 ()
Returns Value parsed as a 64-bit unsigned integer.
Int32 ToInt32 ()
Returns Value parsed as a 32-bit signed integer.
UInt32 ToUInt32 ()
Returns Value parsed as a 32-bit unsigned integer.
Int16 ToInt16 ()
Returns Value parsed as a 16-bit signed integer.
UInt16 ToUInt16 ()
Returns Value parsed as a 16-bit unsigned integer.
sbyte ToInt8 ()
Returns Value parsed as an 8-bit signed integer.
byte ToUInt8 ()
Returns Value parsed as an 8-bit unsigned integer.
float ToFloat ()
Returns Value parsed as a single-precision floating point number.
double ToDouble ()
Returns Value parsed as a double-precision floating point number.
bool ToBool ()
Returns Value parsed as a boolean value.
override string ToString ()
Returns the key as it would appear in a file.
Static Public Member Functions
static Key CreateFromLine (string line)
Parses a line from a file and assigns the data to a new instance.
Properties
string Name [get, set]
The name of the key.
string Value [get, set]
The value of the key.
Detailed Description
A key/property containing a name and value.
Constructor & Destructor Documentation
Key()
SharpIni.Key.Key (string name = null, string value = null)
Constructs the instance with an optional name and value.
If the given name is invalid, Name will be set to string.Empty (See Naming.IsValid(string)).
If the given value is null, Value will be set to string.Empty (See Naming.IsValid(string)).
Parameters
name The name of the key.
value The value of the key.
References SharpIni.Naming.IsValid(), SharpIni.Key.Name, and SharpIni.Key.Value.
Member Function Documentation
CreateFromLine()
static Key SharpIni.Key.CreateFromLine (string line) static
Parses a line from a file and assigns the data to a new instance.
Parameters
line The line to parse.
Returns
The newly created instance, null on failure.
References SharpIni.Key.Key(), and SharpIni.Key.LoadFromLine().
LoadFromLine()
bool SharpIni.Key.LoadFromLine (string line)
Parses a line from a file and assigns the data to the instance.
Parameters
line The line to parse.
Returns
True if the string was parsed as a key and the name is valid, otherwise false.
References SharpIni.Debug.Log(), SharpIni.Key.Name, and SharpIni.Key.Value.
ToBool()
bool SharpIni.Key.ToBool ()
Returns Value parsed as a boolean value.
Exceptions
ArgumentNullException If Value is null.
FormatException If Value is formatted incorrectly for the type.
References SharpIni.Key.ToInt32(), and SharpIni.Key.Value.
ToDouble()
double SharpIni.Key.ToDouble ()
Returns Value parsed as a double-precision floating point number.
Exceptions
ArgumentNullException If Value is null.
FormatException If Value is formatted incorrectly for the type.
OverflowException If the parsed value of Value is out of range for the type.
References SharpIni.Key.Value.
ToFloat()
float SharpIni.Key.ToFloat ()
Returns Value parsed as a single-precision floating point number.
Exceptions
ArgumentNullException If Value is null.
FormatException If Value is formatted incorrectly for the type.
OverflowException If the parsed value of Value is out of range for the type.
References SharpIni.Key.Value.
ToInt16()
Int16 SharpIni.Key.ToInt16 ()
Returns Value parsed as a 16-bit signed integer.
Exceptions
ArgumentNullException If Value is null.
FormatException If Value is formatted incorrectly for the type.
OverflowException If the parsed value of Value is out of range for the type.
References SharpIni.Key.Value.
ToInt32()
Int32 SharpIni.Key.ToInt32 ()
Returns Value parsed as a 32-bit signed integer.
Exceptions
ArgumentNullException If Value is null.
FormatException If Value is formatted incorrectly for the type.
OverflowException If the parsed value of Value is out of range for the type.
References SharpIni.Key.Value.
ToInt64()
Int64 SharpIni.Key.ToInt64 ()
Returns Value parsed as a 64-bit signed integer.
Exceptions
ArgumentNullException If Value is null.
FormatException If Value is formatted incorrectly for the type.
OverflowException If the parsed value of Value is out of range for the type.
References SharpIni.Key.Value.
ToInt8()
sbyte SharpIni.Key.ToInt8 ()
Returns Value parsed as an 8-bit signed integer.
Exceptions
ArgumentNullException If Value is null.
FormatException If Value is formatted incorrectly for the type.
OverflowException If the parsed value of Value is out of range for the type.
References SharpIni.Key.Value.
ToString()
override string SharpIni.Key.ToString ()
Returns the key as it would appear in a file.
Returns
A string representing the key as it would appear in a file. (Name = Value).
References SharpIni.Key.Name, and SharpIni.Key.Value.
ToUInt16()
UInt16 SharpIni.Key.ToUInt16 ()
Returns Value parsed as a 16-bit unsigned integer.
Exceptions
ArgumentNullException If Value is null.
FormatException If Value is formatted incorrectly for the type.
OverflowException If the parsed value of Value is out of range for the type.
References SharpIni.Key.Value.
ToUInt32()
UInt32 SharpIni.Key.ToUInt32 ()
Returns Value parsed as a 32-bit unsigned integer.
Exceptions
ArgumentNullException If Value is null.
FormatException If Value is formatted incorrectly for the type.
OverflowException If the parsed value of Value is out of range for the type.
References SharpIni.Key.Value.
ToUInt64()
UInt64 SharpIni.Key.ToUInt64 ()
Returns Value parsed as a 64-bit unsigned integer.
Exceptions
ArgumentNullException If Value is null.
FormatException If Value is formatted incorrectly for the type.
OverflowException If the parsed value of Value is out of range for the type.
References SharpIni.Key.Value.
ToUInt8()
byte SharpIni.Key.ToUInt8 ()
Returns Value parsed as an 8-bit unsigned integer.
Exceptions
ArgumentNullException If Value is null.
FormatException If Value is formatted incorrectly for the type.
OverflowException If the parsed value of Value is out of range for the type.
References SharpIni.Key.Value.
Property Documentation
Name
string SharpIni.Key.Name get set
The name of the key.
Exceptions
ArgumentException If assigned to an invalid name (See Naming.IsValid(string)).
Value
string SharpIni.Key.Value get set
The value of the key.
The documentation for this class was generated from the following file:
SharpIni/Key.cs